services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=resume'
      - 'POSTGRES_PASSWORD=newpassword'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
