services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=resume'
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - '5433:5433'
